# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [44]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [45]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [46]:
print(np.version)

<module 'numpy.version' from 'c:\\Users\\itayf\\anaconda3\\envs\\mamba\\Lib\\site-packages\\numpy\\version.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [47]:
Z = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [48]:
print(Z.itemsize * Z.size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [49]:
# %run python -c "import numpy; numpy.info(numpy.add)"`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [50]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [51]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [52]:
Z_fliped = np.flip(Z)
print(Z_fliped)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [53]:
Z = np.arange(0,9)
Z = np.reshape(Z,[3,3])
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [54]:
Z = np.asarray([1,2,0,0,4,0])
print(Z.nonzero())

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [55]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [56]:
print(np.random.random((3,3,3)))

[[[0.89156498 0.92433968 0.32014743]
  [0.41436932 0.15325647 0.56913931]
  [0.76407687 0.1020946  0.69272151]]

 [[0.5844693  0.31091943 0.04775854]
  [0.7701539  0.34196922 0.91258391]
  [0.90401123 0.57868846 0.49774939]]

 [[0.69369908 0.78044176 0.12439319]
  [0.96783752 0.37856453 0.23409279]
  [0.52024271 0.26826816 0.21211197]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
Z = np.random.random((10,10))
z_min = np.min(Z)
z_max = np.max(Z)
print(z_min, z_max)

0.026270329065135156 0.9867533116238186


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
Z = np.random.random(30)
print(np.mean(Z))

0.43851267045519926


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [59]:
n = 1
Z = np.zeros((n,n))
arr_of_ones_n = np.ones(n)
arr_of_ones_n_1 = np.ones(n+1)
arr_of_ones_n_2 = np.ones(n+2)
halfway_there = np.column_stack((np.rot90(np.column_stack((Z, arr_of_ones_n))), arr_of_ones_n_1))
Z_border = np.column_stack((np.rot90(np.column_stack((np.rot90(halfway_there), arr_of_ones_n_1))), arr_of_ones_n_2))
print(Z_border)
answer(16)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [60]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [61]:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [62]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [63]:
Z = [[1 if i%2 == j%2 else 0 for i in range(8)] for j in range(8)]
print(np.asarray(Z))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [64]:
(3,1,2)
print(np.unravel_index(99,(6,7,8), order="F"))
answer(20)

(3, 2, 2)
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [65]:
Z = np.asarray(((1,0),(0,1)))
print(np.tile(Z,(4,4)))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [66]:
Z = np.random.random((5,5))
col_means = np.mean(Z,axis=1)
res = (Z-col_means) / np.std(Z, axis=1)
print(res)

[[ 0.23018519 -2.71973989 -1.08941386  1.53025169  1.83784824]
 [-1.11244313  1.53148816 -1.56564212  0.54356463  0.35518319]
 [ 1.05229679 -0.84896796  1.00501156  1.25287387  1.68149608]
 [-1.53323483  0.65192908 -1.7765427  -0.89888224  2.07505668]
 [-0.56235264  0.82362757 -3.0910742  -1.05704645  1.12891762]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [67]:
dt = np.dtype([('R',np.ubyte), ('G',np.ubyte), ('B',np.ubyte), ('A',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [68]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A@B)

[[0.23455206 0.36713446]
 [0.75657412 0.86670844]
 [0.23623189 0.50085177]
 [0.47552183 0.80609441]
 [0.51028179 0.86285377]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [69]:
A = np.arange(10)
A[(A<9) & (A>2)] *= -1
print(A)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [70]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [71]:
Z = np.arange(10)
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [72]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\itayf\AppData\Local\Temp\ipykernel_217128\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\itayf\AppData\Local\Temp\ipykernel_217128\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\itayf\AppData\Local\Temp\ipykernel_217128\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [73]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 9. -8.  9. -2. -2.  1.  7. -9.  8. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [74]:
z = np.arange(19)
a = np.arange(10)
print(np.intersect1d(z,a))

[0 1 2 3 4 5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\itayf\AppData\Local\Temp\ipykernel_217128\2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [76]:
A = np.random.random((10,10))
B = np.random.random((10,10))
A += B
A *= (-A/2)
print(A)
answer(35)

[[-0.40166741 -0.12609164 -0.10343447 -1.04903791 -0.05225222 -0.85700905
  -0.2939458  -0.53994801 -0.19764921 -1.06355393]
 [-0.14167389 -0.35667915 -0.39375684 -0.06709037 -0.93556716 -1.49960694
  -1.14919529 -0.47439924 -0.92766494 -0.34960475]
 [-0.59208701 -0.50558448 -0.02227814 -0.33131123 -0.07286621 -0.1203571
  -0.30969537 -1.59011727 -0.08554523 -1.41332983]
 [-0.92788976 -0.15720799 -0.2602241  -0.08239922 -1.27986963 -0.47802162
  -0.31039327 -1.1807794  -0.33535827 -0.81530667]
 [-0.3446295  -1.20309381 -1.13898237 -0.01655667 -0.32359979 -0.58662118
  -0.06342342 -0.52087676 -0.56407968 -0.59575426]
 [-0.55519679 -0.31528764 -1.1729274  -1.01967544 -0.8009901  -1.12159314
  -0.30170101 -0.56985927 -1.17937593 -0.52372591]
 [-0.20786577 -1.19665962 -0.43767309 -0.35130358 -0.15095273 -0.21495132
  -1.6108891  -0.20659906 -0.40823059 -0.06647669]
 [-0.38659426 -0.56530897 -0.19248879 -0.63440481 -0.16871704 -0.17840705
  -0.76437171 -0.37685421 -0.39300006 -0.02117866]
 

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [77]:
A = np.arange(0,5)
A_stacked = np.tile(A,(5,1))
print(A_stacked)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [78]:
def ten_gen():
    for i in range(10):
        yield i

g = ten_gen()
a = np.fromiter(g,dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [79]:
a = np.random.randint(0,10, 10)
a = np.sort(a)
print(a)

[0 0 4 4 5 6 7 7 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [80]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [81]:
A = np.random.random((3,3))
B = np.random.random((3,3))
print(np.all(A==B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [82]:
A = np.random.random((4,6))
A.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [83]:
cartisian = np.random.random((10,2))
radiuses = np.sqrt(np.sum(cartisian**2, axis=1))
phis = np.arctan2(cartisian[:,0], cartisian[:,1])
polar = np.vstack((radiuses*np.cos(phis), radiuses*np.sin(phis))).T
print(polar.shape)


(10, 2)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [84]:
A = np.random.randint(0,10,size=10)
m = A.max()
A[A == m] = 0
print(A)

[8 2 0 6 0 6 6 3 2 8]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [85]:
Z = np.zeros((5,5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [104]:
X = np.arange(10)
Y = np.arange(10) + 0.5
Cauchy_mat = 1/np.subtract.outer(X,Y)
print(Cauchy_mat)
answer(47)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [106]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.random((20,20))
print(Z)

[[0.49792098 0.66310759 0.79830272 0.69101029 0.2800271  0.43960506
  0.11390084 0.93727895 0.60457729 0.81905977 0.58748826 0.57309237
  0.12200914 0.51332457 0.34597092 0.49412644 0.83671307 0.65784387
  0.96578611 0.138635  ]
 [0.70546347 0.10797747 0.21274293 0.2311649  0.0598838  0.57922271
  0.6213956  0.52599974 0.70464919 0.68066463 0.80585846 0.80160927
  0.84623373 0.38302897 0.96624782 0.17548004 0.98517295 0.07060298
  0.99837861 0.98959381]
 [0.46312455 0.43585787 0.35540248 0.20042248 0.69062404 0.2951072
  0.89432291 0.64414743 0.31131747 0.69252628 0.34802036 0.43906715
  0.48275934 0.49676002 0.66274541 0.67881391 0.80227139 0.92983183
  0.58365933 0.25624895]
 [0.62562534 0.97532345 0.55605201 0.18594983 0.11427259 0.42797149
  0.22077247 0.87815312 0.05871524 0.08466349 0.7205543  0.76293931
  0.30711624 0.73358164 0.31857309 0.30357529 0.78591378 0.59703184
  0.75218938 0.63789697]
 [0.74164131 0.42618225 0.42195391 0.12885035 0.1687226  0.32796834
  0.91458537 0.29

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [108]:
Z = np.random.uniform(10, 30, size=10)
given_scalar = 19
idx = np.abs(Z-given_scalar).argmin()
print(idx)

9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [113]:
X = np.zeros(shape=(3,3), dtype=[("red", int), ("green", int), ("blue", int), ("pos",[("x", float), ("y", float)])])
print(X)
answer(51)

[[(0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.))]
 [(0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.))]
 [(0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.)) (0, 0, 0, (0., 0.))]]
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [124]:
X = np.random.random(size=(10,2))
D = np.sqrt((X[:, np.newaxis, :] - X[np.newaxis,:,:])**2).sum(axis=2)

[[0.         0.63603791 0.13679825 0.76462704 0.56659421 0.95530576
  0.22496878 0.70642503 0.40051916 0.50254041]
 [0.63603791 0.         0.49923965 1.40066495 0.56347507 1.59134366
  0.61599366 0.92127622 1.03655706 0.7015616 ]
 [0.13679825 0.49923965 0.         0.9014253  0.53517615 1.09210401
  0.25638684 0.73784309 0.53731741 0.47112235]
 [0.76462704 1.40066495 0.9014253  0.         0.83718988 0.19067871
  0.78467128 0.54192356 0.54726127 0.69910335]
 [0.56659421 0.56347507 0.53517615 0.83718988 0.         1.02786859
  0.791563   1.27301924 0.47308199 0.13808653]
 [0.95530576 1.59134366 1.09210401 0.19067871 1.02786859 0.
  0.97535    0.67006745 0.5547866  0.88978206]
 [0.22496878 0.61599366 0.25638684 0.78467128 0.791563   0.97535
  0.         0.48145624 0.60772859 0.72750919]
 [0.70642503 0.92127622 0.73784309 0.54192356 1.27301924 0.67006745
  0.48145624 0.         1.08918483 1.20896543]
 [0.40051916 1.03655706 0.53731741 0.54726127 0.47308199 0.5547866
  0.60772859 1.08918483 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [132]:
A = np.random.random(size=(10,10))
A[:] = A.astype(int)
answer(53)

# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [137]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [139]:
Z = np.random.standard_normal(size=(3,3))
print(Z)
answer(56)

[[ 0.79517982  1.09915523 -1.31724862]
 [ 0.16151457 -0.43746586 -0.80540572]
 [-0.73060147  0.19565505 -0.39569823]]
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [153]:
n = 6
p = 4
elem = 88
assert p<=n**2
arr = np.zeros((n,n))
idx = np.arange(n**2)
print(idx)
chosen_idx = np.random.choice(idx, p, replace=False)
print(chosen_idx)
np.put(arr, chosen_idx, elem)
print(arr)
answer(57)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[25  2  6 30]
[[ 0.  0. 88.  0.  0.  0.]
 [88.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0. 88.  0.  0.  0.  0.]
 [88.  0.  0.  0.  0.  0.]]
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [155]:
arr = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(np.mean(arr, axis=1))
print(arr - np.mean(arr, axis=1))
answer(58)

[2. 5. 8.]
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [167]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[6 3 8]
 [2 7 8]
 [0 3 5]]
[[6 3 8]
 [0 3 5]
 [2 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

hint: any, ~


#### 61. Find the nearest value from a given value in an array (★★☆)

In [174]:
arr = np.random.uniform(0,1,10)
v = 0.4
print(np.argmin(np.abs(arr-v)))
print(arr)

6
[0.88751291 0.04379629 0.63287771 0.79510171 0.37890375 0.57298897
 0.37947387 0.85028099 0.5050646  0.91937253]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [179]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [182]:
class myArr(np.ndarray):
    def __new__(cls, array, name=None):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if object is None: return
        self.name = getattr(obj, "name", None)

Z = myArr(np.arange(10), "David")
print(Z - np.random.random(10))

[-0.86013558  0.38137516  1.89107552  2.27293756  3.48074241  4.5276694
  5.3196645   6.06179328  7.67362797  8.15560321]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [188]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2 7 2 9 8 5 8 2 3 4 9 1 6 4 4 5 5 2 3 2]
[1. 2. 6. 3. 4. 4. 2. 2. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [191]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [198]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64
256
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [214]:
arr = np.ones((3,3,3,3))
print(arr.reshape(-1,3,3).shape)
print(arr.reshape(-1,3,3).sum(axis=(-1,-2)))
sum = arr.sum(axis=(-2,-1))
print(sum)
answer(67)

(9, 3, 3)
[9. 9. 9. 9. 9. 9. 9. 9. 9.]
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [216]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

0.5594636583520726
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [219]:
X = np.random.random(size=(5,5))
Y = np.random.random(size=(5,5))
print((X@Y).diagonal())

[0.60383576 1.32647835 0.61049924 1.19870153 1.12086242]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [234]:
a = np.array((1,2,3,4,5))
nz = 3
Z = np.zeros(len(a) + (len(a-1)*nz))
Z[::4] = a
print(Z)
answer(70)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [245]:
Z = np.ones((5,5,3))
X = np.ones((5,5))
print(Z * X[:,:,np.newaxis])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★)

In [262]:
A = np.arange(9).reshape(3,3)
A[[1,2]] = A[[2,1]]
print(A)
answer(72)

[[0 1 2]
 [6 7 8]
 [3 4 5]]
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [269]:
faces = np.random.randint(0,100,(10,3))
print(faces.repeat(2,axis=1))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F)
answer(73)

[[32 32  3  3 39 39]
 [76 76 52 52  4  4]
 [11 11 84 84 32 32]
 [41 41 39 39 32 32]
 [45 45 47 47 37 37]
 [10 10 31 31 89 89]
 [40 40  9  9 17 17]
 [60 60 79 79 78 78]
 [61 61  4  4  2  2]
 [47 47 79 79 37 37]]
[[32  3  3 39 39 32]
 [76 52 52  4  4 76]
 [11 84 84 32 32 11]
 [41 39 39 32 32 41]
 [45 47 47 37 37 45]
 [10 31 31 89 89 10]
 [40  9  9 17 17 40]
 [60 79 79 78 78 60]
 [61  4  4  2  2 61]
 [47 79 79 37 37 47]]
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [286]:
C = [0,1,2,3,4,4,6]
A = np.array([])
for i, elem in np.ndenumerate(C):
    print(i[0],elem)
    A = np.append(A, i*np.ones(elem))
print(np.bincount(A.astype(int64)))
answer(74)
C = np.bincount([0,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

0 0
1 1
2 2
3 3
4 4
5 4
6 6
[0 1 2 3 4 4 6]
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)
[0 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [289]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

18


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [290]:
Z = np.arange(24)
print(sliding_window_view(Z, window_shape=3))

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [292]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [297]:
P1 = np.random.random((10,2))
P2 = np.random.random((10,2))
p = np.array((1,0))
D = np.abs(((P2-P1)*p[[1,0]]) + P2*P1[:,[1,0]]) / np.sqrt((P2-P1)**2)
print(D)
answer(78)

[[4.38310607 2.44931368]
 [2.94683611 1.88599513]
 [0.18345153 0.23177866]
 [0.43213844 0.56403721]
 [0.79768779 1.22165342]
 [0.26719157 1.57070342]
 [0.66030779 2.28350025]
 [3.113084   0.91731747]
 [0.19450323 1.13294609]
 [2.35060396 2.98660418]]
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)
